apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nacos-cluster
  namespace: dawn-system
spec:
  serviceName: nacos-headless
  replicas: 3
  selector:
    matchLabels:
      app: nacos-cluster
  template:
    metadata:
      labels:
        app: nacos-cluster
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values:
                      - nacos
              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: nacos-server
          imagePullPolicy: IfNotPresent
          image: nacos/nacos-server:latest
          volumeMounts:
            - name: nacos-vct
              mountPath: /home/nacos/logs/
              subPath: nacos/logs
            - name: nacos-vct
              mountPath: /home/nacos/data/
              subPath: nacos/data
          resources:
            requests:
              memory: "2Gi"
              cpu: "2000m"
          ports:
            - containerPort: 8848
              name: client
            - containerPort: 9848
              name: client-rpc
            - containerPort: 9849
              name: raft-rpc
          env:
            - name: NACOS_REPLICAS
              value: "3"
            - name: MYSQL_SERVICE_HOST
              valueFrom:
                configMapKeyRef:
                  name: nacos-mysql-config
                  key: mysql.host
            - name: MYSQL_SERVICE_DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: nacos-mysql-config
                  key: mysql.db
            - name: MYSQL_SERVICE_PORT
              valueFrom:
                configMapKeyRef:
                  name: nacos-mysql-config
                  key: mysql.port
            - name: MYSQL_SERVICE_USER
              valueFrom:
                configMapKeyRef:
                  name: nacos-mysql-config
                  key: mysql.user
            - name: MYSQL_SERVICE_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: nacos-mysql-config
                  key: mysql.password
            - name: MODE
              value: "cluster"
            - name: NACOS_SERVER_PORT
              value: "8848"
            - name: PREFER_HOST_MODE
              value: "hostname"
            - name: NACOS_SERVERS
              value: "nacos-cluster-0.nacos-headless.dawn-system.svc.cluster.local:8848 nacos-cluster-1.nacos-headless.dawn-system.svc.cluster.local:8848 nacos-cluster-2.nacos-headless.dawn-system.svc.cluster.local:8848"
  volumeClaimTemplates:
    - metadata:
        namespace: default
        name: nacos-vct
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: longhorn
        resources:
          requests:
            storage: 20Gi