---
apiVersion: v1
kind: Service
metadata:
  name: nacos-headless
  namespace: dawn-system
spec:
  clusterIP: None
  ports:
  - port: 8848
    name: server
    protocol: TCP
    targetPort: 8848
  - port: 9848
    name: client-rpc
    protocol: TCP
    targetPort: 9848
  - port: 9849
    name: raft-rpc
    protocol: TCP
    targetPort: 9849
  selector:
    app: nacos-cluster
  type: ClusterIP
  sessionAffinity: None
---
apiVersion: v1
kind: Service
metadata:
  name: nacos-service
  namespace: dawn-system
spec:
  externalIPs:
  - 172.29.18.201
  ports:
  - port: 8848
    name: server
    protocol: TCP
    targetPort: 8848
  - port: 9848
    name: client-rpc
    protocol: TCP
    targetPort: 9848
  - port: 9849
    name: raft-rpc
    protocol: TCP
    targetPort: 9849
  selector:
    app: nacos-cluster
  type: ClusterIP
  sessionAffinity: None